version: "3.1"
services:
  web:
    build: .
    volumes:
      - .:/var/run/crusher
      - assets:/var/www/assets
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: crusher
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: crusher
      AWS_ACCESS_KEY: $MINIO_ACCESS_KEY
      AWS_SECRET_KEY: $MINIO_SECRET_KEY
    restart: unless-stopped
    # command: "gunicorn -b 0.0.0.0:8080 crusher.wsgi"
    command: "python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db
  # caddy:
  #   image: caddy:2.1.1-alpine
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - assets:/var/www/assets:ro
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: unless-stopped
  db:
    image: mariadb:10
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: crusher
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: crusher
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
  storage:
    image: minio/minio
    volumes:
      - ./media:/data
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    command: ["server", "/data"]
volumes:
  mariadb_data:
  assets:
  bucket_data:
