version: "3.1"
services:
  web:
    build: .
    volumes:
      - .:/var/run/crusher
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: crusher
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: crusher
    restart: unless-stopped
    command: "gunicorn -b 0.0.0.0:8080 crusher.wsgi"
    depends_on:
      - db
  db:
    image: mariadb:10
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: crusher
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: crusher
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
volumes:
  mariadb_data:
