version: "3.1"
services:
  web:
    build: .
    volumes:
      - .:/var/run/crusher
      - assets:/var/www/assets
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: crusher
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: crusher
      AWS_ACCESS_KEY: $MINIO_ACCESS_KEY
      AWS_SECRET_KEY: $MINIO_SECRET_KEY
      AWS_S3_ENDPOINT_URL: $AWS_S3_ENDPOINT_URL
    restart: unless-stopped
    # command: "gunicorn -b 0.0.0.0:8080 crusher.wsgi"
    command: "python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db
  db:
    image: mariadb:10
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: crusher
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: crusher
    restart: unless-stopped
  storage:
    image: minio/minio
    volumes:
      - bucket_data:/data
    command: ["server", "/data"]
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    ports:
      - "9000:9000"
volumes:
  mariadb_data:
  assets:
  bucket_data:
