# Generated by Django 3.1.4 on 2020-12-17 01:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('mobile', models.CharField(blank=True, max_length=256)),
                ('mailing_address', models.TextField(blank=True)),
                ('billing_address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Draft'), (1, 'Open'), (2, 'Paid Partial'), (3, 'Paid Full'), (4, 'Closed'), (-1, 'Void')], default=0)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('paid_balance', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=32)),
                ('upc', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=256)),
                ('mailing_address', models.TextField(blank=True)),
                ('billing_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('default_quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=32)),
                ('default_price', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=32)),
                ('units', models.CharField(blank=True, default='unit', max_length=32)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.item')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=32)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=32)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='app.invoice')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sku')),
            ],
        ),
    ]
