# Generated by Django 3.1.4 on 2020-12-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='company',
        ),
    ]
