# Generated by Django 3.1.4 on 2020-12-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='units',
            field=models.CharField(blank=True, default='unit', max_length=32),
        ),
    ]
