# Generated by Django 3.1.4 on 2020-12-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='data',
            new_name='metadata',
        ),
    ]
