# Generated by Django 3.1.4 on 2020-12-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20201217_1522"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="client",
        ),
        migrations.AddField(
            model_name="invoice",
            name="job",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.job"
            ),
        ),
    ]
