# Generated by Django 3.1.4 on 2020-12-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20201216_2213"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="upc",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
