# Generated by Django 3.1.4 on 2020-12-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201217_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
