# Generated by Django 3.1.4 on 2020-12-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_staff_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='line_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lineitem'),
        ),
        migrations.AddField(
            model_name='credit',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
