# Generated by Django 3.1.4 on 2020-12-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201217_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vessel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vessel'),
        ),
    ]
