# Generated by Django 3.1.4 on 2020-12-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_auto_20201222_0135"),
    ]

    operations = [
        migrations.AddField(
            model_name="renderedform",
            name="rendering_data",
            field=models.JSONField(null=True),
        ),
    ]
