# Generated by Django 3.1.4 on 2020-12-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201217_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='maximum_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='maximum_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='minium_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
    ]
