# Generated by Django 3.1.4 on 2020-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_formtemplate_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='default_fields',
            field=models.JSONField(null=True),
        ),
    ]
