# Generated by Django 3.1.4 on 2020-12-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201217_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vessel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='app.vessel'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.client'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='app.client'),
        ),
    ]
