# Generated by Django 3.1.4 on 2020-12-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_renderedform_rendering_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renderedform',
            old_name='rendering_client',
            new_name='client',
        ),
    ]
