# Generated by Django 3.1.4 on 2020-12-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_auto_20201217_2135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice", name="metadata", field=models.JSONField(null=True),
        ),
    ]
