# Generated by Django 3.1.4 on 2020-12-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201217_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
