# Generated by Django 3.1.4 on 2020-12-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='minium_quantity',
            new_name='minimum_quantity',
        ),
    ]
