# Generated by Django 3.1.4 on 2020-12-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20201219_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='id',
            new_name='uid',
        ),
    ]
