# Generated by Django 3.1.4 on 2020-12-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_auto_20201219_2300"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="image",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
