# Generated by Django 3.1.4 on 2020-12-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_auto_20201220_1341"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment", old_name="object_uid", new_name="object_id",
        ),
    ]
